.PHONY: default
default: build lint

PATH_TO_ROOT:=../../..
include $(PATH_TO_ROOT)/.shapeapp.mk

include $(PATH_TO_SHAPEAPPMK)/components/organs/apisvr-proto/default.mk

.PHONY: test
test:
	@echo "No tests in apisvr/proto"
