APP_BASE_NAME=svelte-connect-todo
APP_MYSQL_DB_NAME=$(APP_BASE_NAME)-db1
GOOGLE_CLOUD_PROJECT_LOCAL=$(APP_BASE_NAME)-gcp-project1
APP_FIREBASE_API_KEY?=firebase-api-key-dummy1

.PHONY: config-envs
config-envs:
	@echo "APP_BASE_NAME=$(APP_BASE_NAME)"
	@echo "APP_MYSQL_DB_NAME=$(APP_MYSQL_DB_NAME)"
	@echo "GOOGLE_CLOUD_PROJECT_LOCAL=$(GOOGLE_CLOUD_PROJECT_LOCAL)"
	@echo "APP_FIREBASE_API_KEY=$(APP_FIREBASE_API_KEY)"
