APP_BASE_NAME=svelte-connect-todo
APP_MYSQL_DB_NAME=$(APP_BASE_NAME)-db1
GOOGLE_CLOUD_PROJECT_LOCAL=$(APP_BASE_NAME)-gcp-project1
APP_FIREBASE_API_KEY?=firebase-api-key-dummy1

CONFIG_VARS=APP_BASE_NAME APP_MYSQL_DB_NAME GOOGLE_CLOUD_PROJECT_LOCAL APP_FIREBASE_API_KEY
CONFIG_ENVS=$(foreach v,$(CONFIG_VARS),$(v)=$($(v)))
