GOOGLE_CLOUD_PROJECT?=
GCP_REGION?=asia-northeast1

GCP_PROJECT_ID=$(GOOGLE_CLOUD_PROJECT)

GCLOUD=gcloud --project $(GOOGLE_CLOUD_PROJECT)

DOCKER_IMAGE_REGISTRY_USER?=akima

APP_STAGE_TYPE=production
