GOOGLE_CLOUD_PROJECT?=
GCP_REGION?=asia-northeast1

GCP_PROJECT_ID=$(GOOGLE_CLOUD_PROJECT)

GCLOUD=gcloud --project $(GOOGLE_CLOUD_PROJECT)

APP_CONTAINER_REPOSITORY?=akima

APP_STAGE_TYPE=production
