# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: backends apisvr proto CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/backends-apisvr-proto.yml"
      - ".gitignore"
      - ".gitmodules"
      - ".config.mk"
      - ".shapeapp.mk"
      - ".tool-versions"
      - "backends/applib/**"
      - "backends/biz/**"
      - "vendor/shapeappmk"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "backends/biz/go.mod"

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: build
        run: make build
        working-directory: ./backends/apisvr/proto

      - name: lint
        run: make lint
        working-directory: ./backends/apisvr/proto

      - name: buf-dep-update
        run: make buf-dep-update
        working-directory: ./backends/apisvr/proto

      - name: generate
        run: make generate
        working-directory: ./backends/apisvr/proto

      - name: git-check
        run: make git-check
        working-directory: ./backends/apisvr/proto
