# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: backends biz CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/backends-biz.yml"
      - ".gitignore"
      - ".gitmodules"
      - ".config.mk"
      - ".shapeapp.mk"
      - ".tool-versions"
      - "backends/applib/**"
      - "backends/biz/**"
      - "backends/test/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "backends/biz/go.mod"

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker version
          docker compose version

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: build
        run: make build
        working-directory: ./backends/biz

      - name: lint
        run: make lint
        working-directory: ./backends/biz

      - name: test
        run: make test
        working-directory: ./backends/biz
