# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: frontends uisvr CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/frontends-uisvr.yml"
      - ".gitignore"
      - ".config.mk"
      - ".shapeapp.mk"
      - ".tool-versions"
      - "backends/apisvr/proto/**"
      - "frontends/uisvr/**"
      - "vendor/shapeappmk"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker version
          docker compose version

      - name: build
        run: make build
        working-directory: ./frontends/uisvr

      - name: lint
        run: make lint
        working-directory: ./frontends/uisvr

      - name: docker-image-build
        run: make docker-image-build
        working-directory: ./frontends/uisvr

      - name: npm-run-test-unit
        run: make npm-run-test-unit
        working-directory: ./frontends/uisvr
