# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: stages production uisvr CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/stages-production-apisvr.yml"
      - ".gitignore"
      - ".gitmodules"
      - ".config.mk"
      - ".shapeapp.mk"
      - ".tool-versions"
      - "fontends/**"
      - "stages/production/uisvr/**"
      - "vendor/shapeappmk"

jobs:
  test:
    name: Build Image
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Check docker version
        run: |
          set -x
          docker -v
          docker version
          docker compose version

      - name: build
        run: make build
        working-directory: ./stages/production/uisvr
